### ISSUE TITLE
nagvis with icingaweb2: "As soon as i add a host to my hosts.conf, i'll get a PHP Error"

### ISSUE THREAD

**Issue by nbg12** [NagVis/nagvis#16]
Hello everybody,

we having problem with displaying our nagvis / icinga2 autoMap.

if we define no hosts on our config files, we can open the nagvis and we get no error messages, but as soon we r insert some new hosts on our icinga2 conf files, weg get this error here:

![1](https://cloud.githubusercontent.com/assets/12952205/8745915/8032eb24-2c84-11e5-9f8c-b1d31b833a8d.png)

i have already reinstalled everyhing from the beginning, but without sucess.

++ additional Information ++

- The DEMO maps can be displayed successfully and wihout any problems

![5](https://cloud.githubusercontent.com/assets/12952205/8745985/3eb63556-2c85-11e5-94e0-5782124f5bbd.png)

- The Icinga2 Livestatus Feature is enabled and 100% active

![2](https://cloud.githubusercontent.com/assets/12952205/8745975/2ac74fbc-2c85-11e5-9f39-fd1ae15883c7.png)

- we tried to restart icinga2 service again and again and this works fine without any startup errors and there we can see our new hosts also successcfully and absolutly correct.

So I guess the problem is maybe something with the Socket or maybe something with nagvis config?

We already opended up an issue topic on the monitoring-portal:
http://www.monitoring-portal.org/wbb/index.php?page=Thread&postID=218360&highlight=#post218360

i would be appreciate any hints or help

Thank you very much!

regards

P.S: My config is orignal the default config (only have changed the language settings)

**Comment by nbg12** [comment]
Edit: the funny thing is when i try to change these lines here

UNKNOWN => Array(
                            'normal'   => intval($e[14]),
                            'stale'    => intval($e[15]),
                            'ack'      => intval($e[16]),
                            'downtime' => intval($e[17]),

with "11" instead of "16" or "17" everything works great and my big nagvis map comes up without any error message... but i could not find out wich part of this $e array is responsible for this error message....

**Comment by LaMi-** [comment]
Which NagVis version do you use?

**Comment by nbg12** [comment]
Hey LaMI,

I am using the NagVis Version 1.8

Thx for your help

**Comment by adri-M** [comment]
Hi guys,

Same issue here (using nagvis icingaweb2 integration via plugin).
All was working fine for a while but after small changes in files /etc/icinga2/conf.d/*.conf i have received the error "undefined Offset: 16" on nagvis frontend for my custom Geomap. No error when i use demo maps/geomap.

No error in icinga2 logs; same issue after many icinga2 restarts or stop/start.

### Install details:
VM Debian 8 Jessie with stable debian repos

Repos used for icinga2/icingaweb2 only:
deb http://http.debian.net/debian jessie-backports main
deb http://packages.icinga.org/debian icinga-jessie main

DPKG List
icinga2                              2.4.1-2~debmon8+3   amd64
php5                                 5.6.17+dfsg-0+deb8u1

Tested and reproduced with Nagvis:
nagvis-1.8.5
nagvis-1.9b4 (when tested an other javascript error occured in addition of undefined Offset error)

Module/modifications used for integration in incingaweb2 (but no links with this error, same with/without this modifications)
https://github.com/Icinga/icingaweb2-module-nagvis

### Nagvis config:

> [global]
> file_group="www-data"
> authmodule="CoreAuthModIcingaweb2"
> authorisationmodule="CoreAuthorisationModIcingaweb2"
> logonmodule="LogonIcingaweb2"
> [paths]
> base="/usr/share/nagvis/"
> htmlcgi="/supervision"
> [defaults]
> backend="live_1"
> urltarget="_top"
> hosturl="[htmlcgi]/monitoring/host/show?host=[host_name]"
> hostgroupurl="[htmlcgi]/monitoring/hostgroup/show?hostgroup=[hostgroup_name]"
> serviceurl="[htmlcgi]/monitoring/service/show?host=[host_name]&service=[service_description]"
> servicegroupurl="[htmlcgi]/monitoring/servicegroup/show?servicegroup=[servicegroup_name]"
> mapurl="[htmlcgi]/nagvis/show/map?map=[map_name]"
> headermenu=0
> stylesheet="icingaweb-nagvis-integration.css"
> [index]
> [automap]
> graphvizpath="/usr/bin/"
> [wui]
> [worker]
> [backend_live_1]
> backendtype="mklivestatus"
> socket="unix:/var/run/icinga2/cmd/livestatus"

### Workaround....
Changing lines 997/998 (for nagvis 1.8.5) in file GlobalBackendmklivestatus.php :

>                         UNKNOWN => Array(
>                             'normal'   => intval($e[14]),
>                             'stale'    => intval($e[15]),
>                             'ack'      => intval($e[11]),
>                             'downtime' => intval($e[11]),
>                         ),


Thx for your help;
Adrien

**Comment by LarsMichelsen** [comment]
Hi,

I just tried to reproduce your issue, but was unable to. I used NagVis 1.9b4 together with Icinga2 r2.4.1-1 with the Icinga2 default configuration. I tried to create a regular NagVis map with all kind of objects, an automap.

From my understanding it is this method getHostMemberCounts() of the livestatus backend which is using the following livestatus query that is problematic for you, right? If you want to try the query, please change the host_name "dev" to some existing host.

```
GET services
Filter: host_name = dev
Stats: has_been_checked = 0
Stats: state = 0
Stats: has_been_checked != 0
Stats: scheduled_downtime_depth = 0
Stats: host_scheduled_downtime_depth = 0
Stats: staleness < 1.5
StatsAnd: 5
Stats: state = 0
Stats: has_been_checked != 0
Stats: scheduled_downtime_depth = 0
Stats: host_scheduled_downtime_depth = 0
Stats: staleness >= 1.5
StatsAnd: 5
Stats: state = 0
Stats: has_been_checked != 0
Stats: scheduled_downtime_depth > 0
Stats: host_scheduled_downtime_depth > 0
StatsOr: 2
StatsAnd: 3
Stats: state = 1
Stats: acknowledged = 0
Stats: host_acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: host_scheduled_downtime_depth = 0
Stats: staleness < 1.5
StatsAnd: 6
Stats: state = 1
Stats: acknowledged = 0
Stats: host_acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: host_scheduled_downtime_depth = 0
Stats: staleness >= 1.5
StatsAnd: 6
Stats: state = 1
Stats: acknowledged = 1
Stats: host_acknowledged = 1
StatsOr: 2
StatsAnd: 2
Stats: state = 1
Stats: scheduled_downtime_depth > 0
Stats: host_scheduled_downtime_depth > 0
StatsOr: 2
StatsAnd: 2
Stats: state = 2
Stats: acknowledged = 0
Stats: host_acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: host_scheduled_downtime_depth = 0
Stats: staleness < 1.5
StatsAnd: 6
Stats: state = 2
Stats: acknowledged = 0
Stats: host_acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: host_scheduled_downtime_depth = 0
Stats: staleness >= 1.5
StatsAnd: 6
Stats: state = 2
Stats: acknowledged = 1
Stats: host_acknowledged = 1
StatsOr: 2
StatsAnd: 2
Stats: state = 2
Stats: scheduled_downtime_depth > 0
Stats: host_scheduled_downtime_depth > 0
StatsOr: 2
StatsAnd: 2
Stats: state = 3
Stats: acknowledged = 0
Stats: host_acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: host_scheduled_downtime_depth = 0
Stats: staleness < 1.5
StatsAnd: 6
Stats: state = 3
Stats: acknowledged = 0
Stats: host_acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: host_scheduled_downtime_depth = 0
Stats: staleness >= 1.5
StatsAnd: 6
Stats: state = 3
Stats: acknowledged = 1
Stats: host_acknowledged = 1
StatsOr: 2
StatsAnd: 2
Stats: state = 3
Stats: scheduled_downtime_depth > 0
Stats: host_scheduled_downtime_depth > 0
StatsOr: 2
StatsAnd: 2
Columns: host_name host_alias
```

This query should return rows with 18 columns normally. Seems that it is not doing that in your case. Please confirm this.

**Comment by adri-M** [comment]
Hi Lars,

> From my understanding it is this method getHostMemberCounts() of the livestatus backend which is using the following livestatus query that is problematic for you, right?
Yes it is!
>  If you want to try the query, please change the host_name "dev" to some existing host.
Sorry for my poor coding capcities, i was not able to reproduce your test. How to execute this? By command line i suppose, but where should i mention my host_name ? Please help.

Using full debuging in nagvis.ini.php parameters does not help, same when i enable full debug in debug.php file.

Thx for your help,
Best regards,

**Comment by LarsMichelsen** [comment]
Do you connect to your livestatus via unix or tcp socket? If it's a unix socket you can e.g. use netcat (at least the bsd ones together with the option -U or if available use socat).

An example with the openbsd netcat:

echo -e "GET hosts\nColumns: name" | nc.openbsd -U tmp/run/live

You should get back a list of all your hostnames

You can now copy the query mentioned in my previous post to a file on your disk, e.g. /tmp/query. then you can execute

cat /tmp/query | nc.openbsd -U tmp/run/live

You should get back the response of livestatus. Please post it here.

**Comment by LarsMichelsen** [comment]
Might have been solved with 719e33c. Please check it out either with the next nightly build or the future 1.9b6.

**Comment by JamesHarrison** [comment]
Testing with Icinga v2.4.4 on CentOS 7 and nagvis-1.9-nightly (downloaded at ~1000 UTC on Fri 15th Apr) I still get this error.

I've run `echo -e "GET hosts\nColumns: name" | nc -U /var/run/icinga2/cmd/livestatus` and I get nothing. If I omit the columns filter I get a convincing-looking list back.
```
#0 /var/www/nagvis/share/server/core/classes/GlobalBackendmklivestatus.php(1004): nagvisExceptionErrorHandler(8, 'Undefined offse...', '/var/www/nagvis...', 1004, Array)
#1 /var/www/nagvis/share/server/core/classes/CoreBackendMgmt.php(482): GlobalBackendmklivestatus->getHostMemberCounts(Array, 1, Array)
#2 /var/www/nagvis/share/server/core/classes/CoreBackendMgmt.php(169): CoreBackendMgmt->fetchStateCounts('live_1', 'hostMemberState', 1, Array)
#3 /var/www/nagvis/share/server/core/classes/NagVisMap.php(58): CoreBackendMgmt->execute()
#4 /var/www/nagvis/share/server/core/classes/CoreModMap.php(319): NagVisMap->__construct(Object(GlobalMapCfg), true, true)
#5 /var/www/nagvis/share/server/core/classes/CoreModMap.php(104): CoreModMap->getMapObjects()
#6 /var/www/nagvis/share/server/core/functions/index.php(120): CoreModMap->handleAction()
#7 /var/www/nagvis/share/server/core/ajax_handler.php(58): require('/var/www/nagvis...')
#8 {main}
```

**Comment by gitmopp** [comment]
I had the same problem in nagvis-1.8.5. Update to nagvis-1.9b11 solved the problem for me.
