### ISSUE TITLE
Authentication fails for all users but admin

### ISSUE THREAD

**Issue by tbeisigl** [NagVis/nagvis#266]
Have been banging my head on the wall trying to figure this out for some time now. Have Nagvis version 1.9.14 using the default SQLite3.7.17.
Apache 2.4.6 (CentOS)
PHP version 5.4.16
CentOS7
When I connect to the nagvis website, I get the username and password screen. I can login as admin and edit and create maps and such. I can edit/add/delete users. The users show up in the auth.db file and when I try and login as a user in that auth.db file, the login screen just goes right back to asking for username and password. No error. The nagvis-audit.log file shows that it connected and failed login. The nagvis-audit.log file also shows the correct user number that is in the auth.db file so I know it is reading the correct file, yet can not get it to work.

Did a tcpdump to make sure that the username and password were being sent correctly and they are. Short of thinking this is a bug, I am at a loss. Additionally, if I enter the wrong password for the users that are not working it will give an error of "Error: Authentication failed".

[root@CentOS7-LAB etc]# sqlite3 auth.db
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> select * from users;
1|admin|868103841a2244768b2dbead5dbea2b533940e20
2|guest|a4e74a1d28ec981c945310d87f8d7b535d794cd2
4|miket|2c23510cfe073a944383c6835a72b58165ce561d
5|mtrueblood|fdc92944a5acad93fa70690fd888bc50e961a029
6|troy|4df55749250d7d9d9b6b65cc48d0562687a2136f
sqlite> 

[root@CentOS7-LAB etc]# more ../var/nagvis-audit.log 
2020-07-10 15:13:42 User logged in (admin / 1): CoreAuthModSQLite
2020-07-10 15:13:42 User logged in (admin / 1): CoreAuthModSQLite
2020-07-10 15:13:42 User logged in (admin / 1): CoreAuthModSQLite
2020-07-10 15:13:52 User logged in (miket / 4): CoreAuthModSQLite
2020-07-10 15:13:52 User logged in (miket / 4): CoreAuthModSQLite
2020-07-10 15:13:52 User logged in (miket / 4): CoreAuthModSQLite
2020-07-10 15:13:52 User logged in (miket / 4): CoreAuthModSQLite
2020-07-10 15:13:52 User login failed ( / -1): CoreAuthModSQLite
2020-07-10 15:13:52 User login failed ( / -1): CoreAuthModSQLite
2020-07-10 15:13:52 User login failed ( / -1): CoreAuthModSQLite
2020-07-10 15:14:12 User logged in (admin / 1): CoreAuthModSQLite

**Comment by T100D** [comment]
Looks like this: https://github.com/NagVis/nagvis/issues/204

I thought it was fixed in 1.9.15

**Comment by tbeisigl** [comment]
I just updated to 1.9.20 and the issue is still the same. If I use a valid username(miket) and password, it just goes back the login screen with no error message but logs the "User login failed ( / -1): CoreAuthModSQLite". If I enter a username(miket) with a invalid password, it get an error message that says "Error: Authentication failed." and the audit log shows "login failed (miket / -1): CoreAuthModSQLite".

Seems as though it is not fixed.

**Comment by jdidierpichatext** [comment]
I got the same problem after upgrading. Someone find a solution ?

**Comment by willipl1972** [comment]
nagvis 1.9.44
User login failed ( / -1): CoreAuthModSQLite

I am trying the LDAP method via Apache and it no worky worky: ( do I have to include a UserFile)
nagvis.conf
Alias /nagvis "/usr/local/nagvis/share"

<Directory "/usr/local/nagvis/share">
  Options FollowSymLinks
  AllowOverride All

  <IfModule mod_authz_core.c>
    # Apache >= 2.4
    Require all granted
  </IfModule>
  <IfModule !mod_authz_core.c>
    # Apache < 2.4
    Order allow,deny
    Allow from all
  </IfModule>

  # To enable Nagios basic auth on NagVis use the following options
  # Just uncomment it. Maybe you need to adjust the path to the
  # Auth user file.
  #
  # If you use the NagVis internal auth mechanism based on the web
  # for you won't need this.
  #
  #AuthName "NagVis Access"
  #AuthType Basic
  #AuthUserFile /usr/local/nagios/etc/htpasswd.users
  #Require valid-user
   AuthName "Nagvis Access"
   AuthType Basic
   AuthLDAPURL "ldaps://myldap.exampl.com:636/cn=users,dc=example,dc=com?uid?sub?(uid=*)" TLS
   AuthBasicProvider ldap
   Require valid-user
  
  # With installed and enabled mod_rewrite there are several redirections
  # available to fix deprecated and/or wrong urls. None of those rules is
  # mandatory to get NagVis working.
  <IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /nagvis
    
    # Use mod_rewrite for old url redirection even if there are php files which
    # redirect the queries itselfs. In some cases the mod_rewrite redirect
    # is better than the php redirect.
    #
    # Using the php redirect seems to be better in some cases where https/http servers
    # are mixed. For example in OMD setups where using apache own mode and https in the
    # frontend and http in the backend apache servers.
    #
    # Disabling this redirect by default in the hope that the php direct works better.
    #RewriteCond %{REQUEST_URI} ^/nagvis(/config\.php|/index\.php|/|)(\?.*|)$
    #RewriteRule ^(.*)$ /nagvis/frontend/nagvis-js/%1%2 [R=301,L]
    
    # Redirect old regular map links
    RewriteCond %{REQUEST_URI} ^/nagvis/frontend/(wui|nagvis-js)
    RewriteCond %{QUERY_STRING} map=(.*)
    RewriteRule ^(.*)$ /nagvis/frontend/nagvis-js/index.php?mod=Map&act=view&show=%1 [R=301,L]

    # Without map= param
    RewriteCond %{REQUEST_URI} ^/nagvis/frontend(/wui)?/?(index.php)?$
    RewriteRule ^(.*)$ /nagvis/frontend/nagvis-js/index.php [R=301,L]

    # Redirect old rotation calls
    RewriteCond %{REQUEST_URI} ^/nagvis/frontend/nagvis-js
    RewriteCond %{QUERY_STRING} !mod
    RewriteCond %{QUERY_STRING} rotation=(.*)
    RewriteRule ^(.*)$ /nagvis/frontend/nagvis-js/index.php?mod=Rotation&act=view&show=%1 [R=301,L]
  </IfModule>
</Directory>

nagvis.ini.php
logonmodule="LogonMixed"
logonenvvar="REMOTE_USER"
logonenvcreateuser="1"
logonenvcreaterole="Guests"
