### ISSUE TITLE
Php 7

### ISSUE THREAD

**Issue by Joir2000** [NagVis/nagvis#51]
It looks like Nagvis doesn't work with Php 7.
After installation nagvis/frontend/nagvis-js/index.php shows : 

Error: (0) Methods with the same name as their class will not be constructors in a future version of PHP; StringReader has a deprecated constructor (/usr/share/nagvis/share/server/core/ext/php-gettext-1.0.9/streams.php:48)

#0 /usr/share/nagvis/share/server/core/ext/php-gettext-1.0.9/gettext.inc(42): nagvisExceptionErrorHandler(8192, 'Methods with th...', '/usr/share/nagv...', 48, Array)
#1 /usr/share/nagvis/share/server/core/ext/php-gettext-1.0.9/gettext.inc(42): require()
#2 /usr/share/nagvis/share/server/core/classes/GlobalLanguage.php(48): require_once('/usr/share/nagv...')
#3 /usr/share/nagvis/share/server/core/functions/core.php(55): GlobalLanguage->__construct()
#4 /usr/share/nagvis/share/frontend/nagvis-js/index.php(44): require('/usr/share/nagv...')
#5 {main}

Info about my system :
Linux XYMon 4.4.7-5-ARCH #1 SMP Wed Apr 20 18:41:11 MDT 2016 armv7l GNU/Linux
Apache/2.4.20 (Unix) PHP/7.0.5

**Comment by LarsMichelsen** [comment]
Which NagVis version did you try?

**Comment by Joir2000** [comment]
I tried several ones
The latest one 1.9b6 is having the same result

**Comment by LarsMichelsen** [comment]
PHP fixes have been made in current master some days ago. You could try to install the daily builds.

**Comment by LarsMichelsen** [comment]
I just pushed a fix for the gettext warning. Would be nice if you could try next nightly build from http://nagvis.org/downloads

**Comment by Joir2000** [comment]
The output changed, but it is still not working.

Error: (0) Methods with the same name as their class will not be constructors in a future version of PHP; gettext_reader has a deprecated constructor
URL: /nagvis/frontend/nagvis-js/index.php
File: /usr/local/nagvis/share/server/core/ext/php-gettext-1.0.9/gettext.php
Line: 36
#0 /usr/local/nagvis/share/server/core/ext/php-gettext-1.0.9/gettext.inc(43): nagvisExceptionErrorHandler(8192, 'Methods with th...', '/usr/local/nagv...', 36, Array)
#1 /usr/local/nagvis/share/server/core/ext/php-gettext-1.0.9/gettext.inc(43): require()
#2 /usr/local/nagvis/share/server/core/classes/GlobalLanguage.php(48): require_once('/usr/local/nagv...')
#3 /usr/local/nagvis/share/server/core/functions/core.php(55): GlobalLanguage->__construct()
#4 /usr/local/nagvis/share/frontend/nagvis-js/index.php(41): require('/usr/local/nagv...')
#5 {main}

**Comment by LarsMichelsen** [comment]
I have currently no access to a PHP7 system. But I fixed this specific error. You can try the current build now.

**Comment by Joir2000** [comment]
The current build works pretty good.
Thanks for the quick support.
